"""initial schema

Revision ID: f57ef13847a0
Revises: 
Create Date: 2026-09-29 08:38:52.783407+00:00

迁移编写须知（ADR-007 / TDD-06 §5.3）：

1. **必须向后兼容**
   - 新增表 / 可空字段        → 安全
   - 新增非空字段（有默认值）  → 安全
   - **删除字段**             → 危险，需分两次发布（先停用，再删除）
   - **重命名字段**           → 危险，需分步（加新 → 双写 → 切读 → 删旧）
   原因：回滚时旧代码会找不到字段直接崩溃。

2. **索引与约束要显式命名**
   匿名约束在 MySQL 中会变成 `orders_ibfk_1` 这类名字，
   报错信息里出现这种名字，排障时根本不知道是哪条约束。
   命名规范见 core/db.py 的 NAMING_CONVENTION。

3. **MySQL 的 ALTER 能力有限**
   改列类型、删列、加约束可能需要重建表。
   大表上这些操作会锁表，需评估影响窗口。

4. **不要用 `op.execute("DROP ...")` 做数据清理**
   迁移只负责结构，数据清理属于运维脚本（ops/）。
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f57ef13847a0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_periods',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('shop_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('period_start', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('period_end', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='OPEN', nullable=False),
    sa.Column('closed_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('closed_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('reopen_reason', sa.Text(), nullable=True),
    sa.Column('calculation_snapshot', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounting_periods')),
    sa.UniqueConstraint('tenant_id', 'shop_id', 'period', name='uk_accounting_periods_key'),
    comment='会计期间'
    )
    with op.batch_alter_table('accounting_periods', schema=None) as batch_op:
        batch_op.create_index('idx_accounting_periods_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_accounting_periods_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('alert_rules',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('scope_type', sa.String(length=32), server_default='GLOBAL', nullable=False),
    sa.Column('scope_value', sa.String(length=255), nullable=True),
    sa.Column('condition_expr', mysql.JSON(), nullable=False),
    sa.Column('level', sa.String(length=16), server_default='P2', nullable=False),
    sa.Column('notify_channels', mysql.JSON(), nullable=False),
    sa.Column('notify_roles', mysql.JSON(), nullable=False),
    sa.Column('escalate_after_minutes', sa.Integer(), nullable=True),
    sa.Column('cooldown_minutes', sa.Integer(), server_default='60', nullable=False),
    sa.Column('min_amount', mysql.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default='1', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules')),
    sa.UniqueConstraint('tenant_id', 'rule_code', 'version', name='uk_alert_rules_version'),
    comment='预警规则'
    )
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.create_index('idx_alert_rules_active', ['tenant_id', 'alert_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_alert_rules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('alert_level', sa.String(length=16), server_default='P2', nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('suggestion_actions', mysql.JSON(), nullable=True),
    sa.Column('related_type', sa.String(length=64), nullable=True),
    sa.Column('related_id', sa.String(length=255), nullable=True),
    sa.Column('shop_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('rule_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('dedup_key', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='OPEN', nullable=False),
    sa.Column('notified_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('notified_channels', mysql.JSON(), nullable=True),
    sa.Column('acknowledged_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('acknowledged_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('resolved_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('resolved_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts')),
    comment='预警实例'
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('idx_alerts_dedup', ['dedup_key', 'created_at'], unique=False)
        batch_op.create_index('idx_alerts_open', ['tenant_id', 'status', 'alert_level', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_alerts_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('idx_alerts_type', ['tenant_id', 'alert_type', 'created_at'], unique=False)

    op.create_table('api_call_logs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('shop_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_category', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rate_limited', mysql.TINYINT(display_width=1), server_default='0', nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('request_summary', mysql.JSON(), nullable=True),
    sa.Column('response_summary', mysql.JSON(), nullable=True),
    sa.Column('raw_payload_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('called_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_call_logs')),
    comment='API 调用日志（脱敏）'
    )
    with op.batch_alter_table('api_call_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_api_call_logs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('idx_api_logs_error', ['error_category', 'called_at'], unique=False)
        batch_op.create_index('idx_api_logs_expiry', ['expires_at'], unique=False)
        batch_op.create_index('idx_api_logs_lookup', ['tenant_id', 'platform', 'called_at'], unique=False)

    op.create_table('approval_actions',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('approval_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False, comment='SUBMIT / APPROVE / REJECT / CANCEL / EXPIRE / EXECUTE / ...'),
    sa.Column('actor_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('actor_type', sa.String(length=16), server_default='USER', nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('metadata_json', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_actions')),
    comment='审批动作流水（append-only）'
    )
    with op.batch_alter_table('approval_actions', schema=None) as batch_op:
        batch_op.create_index('idx_approval_actions_approval', ['approval_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_approval_actions_approval_id'), ['approval_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_approval_actions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('approval_rules',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('operation_type', sa.String(length=64), nullable=False),
    sa.Column('conditions', mysql.JSON(), nullable=False),
    sa.Column('approver_roles', mysql.JSON(), nullable=False),
    sa.Column('required_approvals', sa.Integer(), server_default='1', nullable=False),
    sa.Column('timeout_hours', sa.Integer(), server_default='24', nullable=False),
    sa.Column('escalate_hours', sa.Integer(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default='1', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('effective_from', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('effective_to', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_rules')),
    sa.UniqueConstraint('tenant_id', 'rule_code', 'version', name='uk_approval_rules_version'),
    comment='审批触发规则'
    )
    with op.batch_alter_table('approval_rules', schema=None) as batch_op:
        batch_op.create_index('idx_approval_rules_active', ['tenant_id', 'operation_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_approval_rules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('approvals',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('approval_no', sa.String(length=64), nullable=False),
    sa.Column('approval_type', sa.String(length=64), nullable=False, comment='LISTING_PUBLISH / PRICE_UPDATE / REFUND_EXECUTE / ...'),
    sa.Column('risk_level', sa.String(length=16), server_default='MEDIUM', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='PENDING', nullable=False),
    sa.Column('shop_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('payload_before', mysql.JSON(), nullable=True),
    sa.Column('payload_after', mysql.JSON(), nullable=False),
    sa.Column('suggestion_source', sa.String(length=32), server_default='HUMAN', nullable=False),
    sa.Column('ai_confidence', mysql.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('rule_version', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('requested_by', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('request_reason', sa.Text(), nullable=True),
    sa.Column('approved_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('approved_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('executed_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('execution_result', mysql.JSON(), nullable=True),
    sa.Column('rollback_status', sa.String(length=32), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('expires_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals')),
    sa.UniqueConstraint('approval_no', name=op.f('uk_approvals_approval_no')),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uk_approvals_idempotency'),
    comment='审批单'
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index('idx_approvals_expiry', ['expires_at'], unique=False)
        batch_op.create_index('idx_approvals_pending', ['tenant_id', 'status', 'risk_level', 'created_at'], unique=False)
        batch_op.create_index('idx_approvals_requester', ['requested_by'], unique=False)
        batch_op.create_index('idx_approvals_resource', ['tenant_id', 'resource_type', 'resource_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_approvals_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False, comment='如 config.changed / price.updated'),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('before_value', mysql.JSON(), nullable=True),
    sa.Column('after_value', mysql.JSON(), nullable=True),
    sa.Column('actor_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('actor_type', sa.String(length=16), server_default='USER', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('context', mysql.JSON(), nullable=True),
    sa.Column('shop_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events')),
    comment='业务审计（append-only）'
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('idx_audit_events_actor', ['actor_id', 'created_at'], unique=False)
        batch_op.create_index('idx_audit_events_resource', ['tenant_id', 'resource_type', 'resource_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('idx_audit_events_trace', ['trace_id'], unique=False)
        batch_op.create_index('idx_audit_events_type', ['tenant_id', 'event_type', 'created_at'], unique=False)

    op.create_table('category_schemas',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('category_id', sa.String(length=128), nullable=False),
    sa.Column('product_type', sa.String(length=255), nullable=True),
    sa.Column('schema_version', sa.String(length=64), nullable=False),
    sa.Column('schema_json', mysql.JSON(), nullable=False),
    sa.Column('required_fields', mysql.JSON(), nullable=False),
    sa.Column('fetched_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_schemas')),
    sa.UniqueConstraint('platform', 'region', 'category_id', 'schema_version', name='uk_category_schemas_version'),
    comment='类目属性 schema（版本化）'
    )
    with op.batch_alter_table('category_schemas', schema=None) as batch_op:
        batch_op.create_index('idx_category_schemas_lookup', ['platform', 'region', 'category_id', 'fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_category_schemas_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('config_items',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('namespace', sa.String(length=64), nullable=False),
    sa.Column('config_key', sa.String(length=128), nullable=False),
    sa.Column('value', mysql.JSON(), nullable=False),
    sa.Column('value_type', sa.String(length=16), server_default='STRING', nullable=False),
    sa.Column('effective_from', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('effective_to', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('active_key', sa.String(length=192), sa.Computed('IF(effective_to IS NULL, CONCAT(namespace, CHAR(58), config_key), NULL)', persisted=True), nullable=True, comment='生成列：effective_to IS NULL 时为 namespace:config_key，否则 NULL'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_items')),
    comment='统一标量配置（含时间区间）'
    )
    with op.batch_alter_table('config_items', schema=None) as batch_op:
        batch_op.create_index('idx_config_items_lookup', ['tenant_id', 'namespace', 'config_key'], unique=False)
        batch_op.create_index(batch_op.f('idx_config_items_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('uk_config_items_active', ['tenant_id', 'active_key'], unique=True)

    op.create_table('cost_items',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('internal_sku', sa.String(length=128), nullable=False),
    sa.Column('cost_type', sa.String(length=64), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True, comment='数量（用于单位成本）'),
    sa.Column('unit_cost', mysql.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('batch_no', sa.String(length=128), nullable=True),
    sa.Column('period', sa.String(length=16), nullable=True),
    sa.Column('effective_date', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('vat_included', mysql.TINYINT(display_width=1), server_default='0', nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_items')),
    comment='成本项'
    )
    with op.batch_alter_table('cost_items', schema=None) as batch_op:
        batch_op.create_index('idx_cost_items_period', ['tenant_id', 'period'], unique=False)
        batch_op.create_index('idx_cost_items_sku', ['tenant_id', 'internal_sku', 'cost_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_cost_items_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cost_rules',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('params', mysql.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('effective_from', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('effective_to', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default='1', nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_rules')),
    sa.UniqueConstraint('tenant_id', 'rule_code', 'version', name='uk_cost_rules_version'),
    comment='成本规则（版本化）'
    )
    with op.batch_alter_table('cost_rules', schema=None) as batch_op:
        batch_op.create_index('idx_cost_rules_active', ['tenant_id', 'rule_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_cost_rules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('credential_audit_logs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('shop_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('credential_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('operation', sa.String(length=32), nullable=False, comment='操作：READ / CREATE / ROTATE / REVOKE / DECRYPT'),
    sa.Column('actor_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('actor_type', sa.String(length=16), server_default='SYSTEM', nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False, comment='SUCCESS / FAILED'),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credential_audit_logs')),
    comment='凭据审计（append-only）'
    )
    with op.batch_alter_table('credential_audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_cred_audit_actor', ['actor_id', 'created_at'], unique=False)
        batch_op.create_index('idx_cred_audit_shop', ['shop_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_credential_audit_logs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('domain_events',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False, comment='如 approval.approved / listing.submitted'),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('payload', mysql.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('available_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('processed_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_events')),
    comment='领域事件（Outbox）'
    )
    with op.batch_alter_table('domain_events', schema=None) as batch_op:
        batch_op.create_index('idx_domain_events_aggregate', ['aggregate_type', 'aggregate_id'], unique=False)
        batch_op.create_index('idx_domain_events_pending', ['status', 'available_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_domain_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('idx_domain_events_type', ['tenant_id', 'event_type', 'created_at'], unique=False)

    op.create_table('exchange_rates',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('from_currency', sa.String(length=8), nullable=False),
    sa.Column('to_currency', sa.String(length=8), nullable=False),
    sa.Column('rate', mysql.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('rate_type', sa.String(length=32), nullable=False),
    sa.Column('effective_date', mysql.DATETIME(fsp=6), nullable=False, comment='生效日期（UTC）'),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exchange_rates')),
    sa.UniqueConstraint('tenant_id', 'from_currency', 'to_currency', 'rate_type', 'effective_date', name='uk_exchange_rates_key'),
    comment='汇率（多口径）'
    )
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.create_index('idx_exchange_rates_lookup', ['tenant_id', 'from_currency', 'to_currency', 'rate_type', 'effective_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_exchange_rates_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('feature_flags',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('flag_key', sa.String(length=128), nullable=False),
    sa.Column('enabled', mysql.TINYINT(display_width=1), server_default='0', nullable=False),
    sa.Column('rollout_pct', sa.Integer(), server_default='100', nullable=False),
    sa.Column('allowed_shops', mysql.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('updated_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_flags')),
    sa.UniqueConstraint('tenant_id', 'flag_key', name='uk_feature_flags_key'),
    comment='功能开关'
    )
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.create_index('idx_feature_flags_expiry', ['expires_at'], unique=False)

    op.create_table('order_fees',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('shop_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('settlement_id', sa.String(length=255), nullable=True),
    sa.Column('fee_type', sa.String(length=64), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('platform_sku', sa.String(length=255), nullable=True),
    sa.Column('fee_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('raw_payload_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_fees')),
    comment='平台费用明细'
    )
    with op.batch_alter_table('order_fees', schema=None) as batch_op:
        batch_op.create_index('idx_order_fees_order', ['order_id'], unique=False)
        batch_op.create_index('idx_order_fees_settlement', ['shop_id', 'settlement_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_order_fees_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('idx_order_fees_type', ['tenant_id', 'fee_type', 'fee_time'], unique=False)

    op.create_table('order_items',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('platform_sku', sa.String(length=255), nullable=True),
    sa.Column('platform_item_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('item_total', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('discount_total', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('unit_cost', mysql.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('raw_payload_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items')),
    comment='订单行'
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index('idx_order_items_order', ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index('idx_order_items_sku', ['tenant_id', 'platform_sku'], unique=False)
        batch_op.create_index(batch_op.f('idx_order_items_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('shop_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('platform_order_id', sa.String(length=255), nullable=False),
    sa.Column('order_status', sa.String(length=32), server_default='PENDING', nullable=False),
    sa.Column('fulfillment_channel', sa.String(length=32), nullable=True),
    sa.Column('buyer_hash', sa.String(length=128), nullable=True),
    sa.Column('buyer_region', sa.String(length=64), nullable=True),
    sa.Column('buyer_encrypted', sa.VARBINARY(length=4096), nullable=True),
    sa.Column('buyer_nonce', sa.VARBINARY(length=32), nullable=True),
    sa.Column('item_total', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('shipping_total', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('discount_total', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('tax_total', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('grand_total', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('order_time', mysql.DATETIME(fsp=6), nullable=False, comment='下单时间（经营口径）'),
    sa.Column('ship_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('settle_time', mysql.DATETIME(fsp=6), nullable=True, comment='结算时间（财务口径）'),
    sa.Column('anomaly_flag', mysql.TINYINT(display_width=1), server_default='0', nullable=False),
    sa.Column('anomaly_detail', mysql.JSON(), nullable=True),
    sa.Column('raw_order_status', sa.String(length=64), nullable=True),
    sa.Column('raw_payload_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('platform_raw', mysql.JSON(), nullable=True),
    sa.Column('synced_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('shop_id', 'platform_order_id', name='uk_orders_shop_order'),
    comment='订单（平台镜像）'
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('idx_orders_anomaly', ['tenant_id', 'anomaly_flag'], unique=False)
        batch_op.create_index('idx_orders_buyer_hash', ['buyer_hash'], unique=False)
        batch_op.create_index('idx_orders_settle', ['shop_id', 'settle_time'], unique=False)
        batch_op.create_index('idx_orders_shop_time', ['tenant_id', 'shop_id', 'order_time'], unique=False)
        batch_op.create_index('idx_orders_status', ['shop_id', 'order_status', 'order_time'], unique=False)
        batch_op.create_index(batch_op.f('idx_orders_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('permissions',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False, comment='权限点，如 listing:publish'),
    sa.Column('resource', sa.String(length=64), nullable=False, comment='资源，如 listing'),
    sa.Column('action', sa.String(length=64), nullable=False, comment='动作，如 publish'),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_sensitive', mysql.TINYINT(display_width=1), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uk_permissions_code')),
    comment='权限点'
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index('idx_permissions_resource', ['resource'], unique=False)

    op.create_table('platform_capabilities',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), server_default='UNSUPPORTED', nullable=False),
    sa.Column('disabled_until', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('disabled_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_ref', sa.String(length=512), nullable=True),
    sa.Column('verified_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('code_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_capabilities')),
    sa.UniqueConstraint('platform', 'capability', name='uk_platform_capabilities_key'),
    comment='平台能力矩阵'
    )
    with op.batch_alter_table('platform_capabilities', schema=None) as batch_op:
        batch_op.create_index('idx_platform_capabilities_state', ['platform', 'state'], unique=False)

    op.create_table('platform_categories',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('category_id', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('is_leaf', mysql.TINYINT(display_width=1), server_default='0', nullable=False),
    sa.Column('raw_payload_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('synced_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_categories')),
    sa.UniqueConstraint('platform', 'region', 'category_id', name='uk_platform_categories'),
    comment='平台类目缓存'
    )
    with op.batch_alter_table('platform_categories', schema=None) as batch_op:
        batch_op.create_index('idx_platform_categories_parent', ['platform', 'region', 'parent_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_platform_categories_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('price_history',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('shop_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('listing_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('platform_sku', sa.String(length=255), nullable=False),
    sa.Column('old_price', mysql.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('new_price', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('change_pct', mysql.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('approval_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('actor_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_history')),
    comment='价格历史（append-only）'
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index('idx_price_history_sku', ['tenant_id', 'shop_id', 'platform_sku', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_price_history_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('idx_price_history_time', ['tenant_id', 'created_at'], unique=False)

    op.create_table('pricing_rules',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope_type', sa.String(length=32), server_default='GLOBAL', nullable=False),
    sa.Column('scope_value', sa.String(length=255), nullable=True),
    sa.Column('condition_expr', mysql.JSON(), nullable=False),
    sa.Column('action', mysql.JSON(), nullable=False),
    sa.Column('min_price', mysql.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('max_price', mysql.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default='1', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pricing_rules')),
    sa.UniqueConstraint('tenant_id', 'rule_code', 'version', name='uk_pricing_rules_version'),
    comment='定价规则'
    )
    with op.batch_alter_table('pricing_rules', schema=None) as batch_op:
        batch_op.create_index('idx_pricing_rules_active', ['tenant_id', 'scope_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_pricing_rules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('product_attributes',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('product_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('attr_name', sa.String(length=128), nullable=False),
    sa.Column('attr_value', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), server_default='MANUAL', nullable=False),
    sa.Column('ai_model', sa.String(length=128), nullable=True),
    sa.Column('ai_prompt_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_attributes')),
    sa.UniqueConstraint('product_id', 'attr_name', name='uk_product_attributes_name'),
    comment='商品属性'
    )
    with op.batch_alter_table('product_attributes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_product_attributes_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_product_attributes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('product_listings',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('product_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('variant_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('shop_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('platform_sku', sa.String(length=255), nullable=True, comment='平台侧 SKU'),
    sa.Column('platform_item_id', sa.String(length=255), nullable=True, comment='ASIN / item_id'),
    sa.Column('parent_item_id', sa.String(length=255), nullable=True),
    sa.Column('listing_status', sa.String(length=32), server_default='DRAFT', nullable=False, comment='上架状态机状态'),
    sa.Column('last_error_code', sa.String(length=128), nullable=True),
    sa.Column('last_error_msg', sa.Text(), nullable=True),
    sa.Column('submission_id', sa.String(length=255), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('raw_payload_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('platform_raw', mysql.JSON(), nullable=True),
    sa.Column('published_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('last_synced_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_listings')),
    sa.UniqueConstraint('shop_id', 'platform_sku', name='uk_listings_shop_platform_sku'),
    comment='平台刊登实例'
    )
    with op.batch_alter_table('product_listings', schema=None) as batch_op:
        batch_op.create_index('idx_listings_item', ['shop_id', 'platform_item_id'], unique=False)
        batch_op.create_index('idx_listings_product', ['tenant_id', 'product_id'], unique=False)
        batch_op.create_index('idx_listings_shop_status', ['shop_id', 'listing_status'], unique=False)
        batch_op.create_index('idx_listings_submission', ['submission_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_product_listings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('product_variants',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('product_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('variant_sku', sa.String(length=128), nullable=False),
    sa.Column('parent_sku', sa.String(length=128), nullable=True),
    sa.Column('variant_attributes', mysql.JSON(), nullable=False),
    sa.Column('cost_price', mysql.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variants')),
    sa.UniqueConstraint('tenant_id', 'variant_sku', name='uk_product_variants_sku'),
    comment='商品变体'
    )
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.create_index('idx_product_variants_product', ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_product_variants_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_product_variants_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('products',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('internal_sku', sa.String(length=128), nullable=False, comment='内部 SKU（全局唯一）'),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.String(length=128), nullable=True, comment='内部类目'),
    sa.Column('status', sa.String(length=32), server_default='DRAFT', nullable=False),
    sa.Column('main_image', sa.String(length=1024), nullable=True),
    sa.Column('images', mysql.JSON(), nullable=True),
    sa.Column('cost_price', mysql.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('cost_currency', sa.String(length=8), nullable=True),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('attributes', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', mysql.DATETIME(fsp=6), nullable=True, comment='软删除时间（NULL 表示未删除）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('tenant_id', 'internal_sku', name='uk_products_tenant_sku'),
    comment='商品主表'
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('idx_products_brand', ['tenant_id', 'brand'], unique=False)
        batch_op.create_index('idx_products_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('profit_snapshots',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('shop_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('granularity', sa.String(length=16), nullable=False),
    sa.Column('period_key', sa.String(length=32), nullable=False),
    sa.Column('platform_sku', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.String(length=128), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('gross_sales', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('shipping_income', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('discount_total', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('refund_total', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('chargeback_total', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('tax_total', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('net_sales', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('cogs', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('inbound_freight', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('pre_fulfillment_margin', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('platform_commission', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('fulfillment_fee', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('storage_fee', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('return_loss', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('post_fulfillment_margin', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('ad_spend', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('promotion_cost', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('other_variable_cost', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('post_ads_margin', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('tacos', mysql.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('margin_rate', mysql.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('refund_rate', mysql.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('unit_count', sa.Integer(), nullable=False),
    sa.Column('calculation_meta', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profit_snapshots')),
    sa.UniqueConstraint('tenant_id', 'shop_id', 'granularity', 'period_key', 'platform_sku', name='uk_profit_snapshots_key'),
    comment='利润快照'
    )
    with op.batch_alter_table('profit_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_profit_snapshots_lookup', ['tenant_id', 'shop_id', 'granularity', 'period_key'], unique=False)
        batch_op.create_index('idx_profit_snapshots_sku', ['tenant_id', 'platform_sku'], unique=False)
        batch_op.create_index(batch_op.f('idx_profit_snapshots_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('raw_payloads',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('shop_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('payload_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('content', mysql.JSON(), nullable=False),
    sa.Column('content_type', sa.String(length=32), server_default='application/json', nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('contains_pii', mysql.TINYINT(display_width=1), server_default='0', nullable=False),
    sa.Column('expires_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_payloads')),
    comment='原始报文归档（不可变）'
    )
    with op.batch_alter_table('raw_payloads', schema=None) as batch_op:
        batch_op.create_index('idx_raw_payloads_entity', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_raw_payloads_expiry', ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_raw_payloads_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('idx_raw_payloads_type', ['tenant_id', 'platform', 'payload_type', 'created_at'], unique=False)

    op.create_table('refunds',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('shop_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('platform_refund_id', sa.String(length=255), nullable=True),
    sa.Column('refund_type', sa.String(length=32), server_default='FULL', nullable=False),
    sa.Column('reason_code', sa.String(length=128), nullable=True),
    sa.Column('reason_category', sa.String(length=64), nullable=True),
    sa.Column('reason_confidence', mysql.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='REQUESTED', nullable=False),
    sa.Column('risk_level', sa.String(length=16), server_default='LOW', nullable=False),
    sa.Column('auto_decision', mysql.JSON(), nullable=True),
    sa.Column('handled_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('handled_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('returned_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('restock_status', sa.String(length=32), nullable=True, comment='SELLABLE / UNSELLABLE / PENDING'),
    sa.Column('approval_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('raw_payload_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds')),
    sa.UniqueConstraint('shop_id', 'platform_refund_id', name='uk_refunds_shop_platform_id'),
    comment='退款'
    )
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.create_index('idx_refunds_order', ['order_id'], unique=False)
        batch_op.create_index('idx_refunds_reason', ['tenant_id', 'reason_category'], unique=False)
        batch_op.create_index('idx_refunds_status', ['shop_id', 'status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_refunds_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('return_records',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('shop_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('platform_return_id', sa.String(length=255), nullable=False),
    sa.Column('platform_sku', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason_code', sa.String(length=128), nullable=True),
    sa.Column('reason_category', sa.String(length=64), nullable=True),
    sa.Column('restock_status', sa.String(length=32), nullable=True),
    sa.Column('loss_amount', mysql.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('loss_currency', sa.String(length=8), nullable=True),
    sa.Column('returned_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('raw_payload_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_return_records')),
    sa.UniqueConstraint('shop_id', 'platform_return_id', name='uk_return_records_shop_return'),
    comment='退货记录'
    )
    with op.batch_alter_table('return_records', schema=None) as batch_op:
        batch_op.create_index('idx_return_records_order', ['order_id'], unique=False)
        batch_op.create_index('idx_return_records_status', ['tenant_id', 'restock_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_return_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('role_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('permission_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name='uk_role_permissions_role_perm'),
    comment='角色权限关联'
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index('idx_role_permissions_role', ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_role_permissions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('roles',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False, comment='角色编码，如 admin/ops/cs'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_builtin', mysql.TINYINT(display_width=1), server_default='0', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('tenant_id', 'code', name='uk_roles_tenant_code'),
    comment='角色'
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_roles_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('scoring_rubrics',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('rubric_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dimensions', mysql.JSON(), nullable=False),
    sa.Column('total_weight', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('pass_threshold', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('grade_thresholds', mysql.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default='1', nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scoring_rubrics')),
    sa.UniqueConstraint('tenant_id', 'rubric_code', 'version', name='uk_scoring_rubrics_version'),
    comment='选品评分卡'
    )
    with op.batch_alter_table('scoring_rubrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_scoring_rubrics_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('settlement_fees',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('shop_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('settlement_id', sa.String(length=255), nullable=False),
    sa.Column('platform_order_id', sa.String(length=255), nullable=True),
    sa.Column('platform_sku', sa.String(length=255), nullable=True),
    sa.Column('fee_type', sa.String(length=64), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('matched_order_fee_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('is_matched', mysql.TINYINT(display_width=1), server_default='0', nullable=False),
    sa.Column('fee_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('raw_payload_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlement_fees')),
    comment='结算费用明细'
    )
    with op.batch_alter_table('settlement_fees', schema=None) as batch_op:
        batch_op.create_index('idx_settlement_fees_matched', ['tenant_id', 'is_matched'], unique=False)
        batch_op.create_index('idx_settlement_fees_order', ['platform_order_id'], unique=False)
        batch_op.create_index('idx_settlement_fees_settlement', ['shop_id', 'settlement_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_settlement_fees_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('settlement_records',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('shop_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('settlement_id', sa.String(length=255), nullable=False),
    sa.Column('period_start', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('period_end', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('total_amount', mysql.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('reconcile_status', sa.String(length=32), server_default='PENDING', nullable=False),
    sa.Column('discrepancy_amount', mysql.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('discrepancy_detail', mysql.JSON(), nullable=True),
    sa.Column('raw_payload_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlement_records')),
    sa.UniqueConstraint('shop_id', 'settlement_id', name='uk_settlement_records_shop_id'),
    comment='平台结算批次'
    )
    with op.batch_alter_table('settlement_records', schema=None) as batch_op:
        batch_op.create_index('idx_settlement_records_status', ['tenant_id', 'reconcile_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_settlement_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('shop_credentials',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('shop_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('credential_type', sa.String(length=32), server_default='OAUTH', nullable=False, comment='凭据类型：OAUTH / API_KEY / BASIC'),
    sa.Column('status', sa.String(length=32), server_default='ACTIVE', nullable=False),
    sa.Column('encrypted_dek', sa.VARBINARY(length=4096), nullable=False, comment='被主密钥加密的 DEK（nonce 前置）'),
    sa.Column('access_token_encrypted', sa.VARBINARY(length=4096), nullable=True),
    sa.Column('access_token_nonce', sa.VARBINARY(length=32), nullable=True),
    sa.Column('access_token_expires_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('refresh_token_encrypted', sa.VARBINARY(length=4096), nullable=True),
    sa.Column('refresh_token_nonce', sa.VARBINARY(length=32), nullable=True),
    sa.Column('key_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('scopes', mysql.JSON(), nullable=True, comment='已授权的 scope 列表'),
    sa.Column('last_verified_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('revoked_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_credentials')),
    sa.UniqueConstraint('shop_id', 'credential_type', name='uk_shop_credentials_shop_type'),
    comment='店铺凭据（加密）'
    )
    with op.batch_alter_table('shop_credentials', schema=None) as batch_op:
        batch_op.create_index('idx_shop_credentials_expiry', ['access_token_expires_at'], unique=False)
        batch_op.create_index('idx_shop_credentials_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_shop_credentials_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('shops',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False, comment='平台：AMAZON/TIKTOK/TEMU/...'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='店铺名称（我方命名）'),
    sa.Column('platform_shop_id', sa.String(length=255), nullable=True),
    sa.Column('seller_id', sa.String(length=255), nullable=True),
    sa.Column('marketplace_id', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=16), server_default='OTHER', nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('currency', sa.String(length=8), server_default='USD', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='ACTIVE', nullable=False),
    sa.Column('sync_paused', mysql.TINYINT(display_width=1), server_default='0', nullable=False),
    sa.Column('sync_paused_reason', sa.Text(), nullable=True),
    sa.Column('platform_config', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', mysql.DATETIME(fsp=6), nullable=True, comment='软删除时间（NULL 表示未删除）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shops')),
    sa.UniqueConstraint('tenant_id', 'platform', 'name', name='uk_shops_tenant_platform_name'),
    comment='店铺'
    )
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.create_index('idx_shops_platform', ['tenant_id', 'platform'], unique=False)
        batch_op.create_index('idx_shops_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_shops_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('sku_mappings',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('internal_sku', sa.String(length=128), nullable=False),
    sa.Column('shop_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_sku', sa.String(length=255), nullable=False),
    sa.Column('platform_item_id', sa.String(length=255), nullable=True),
    sa.Column('is_primary', mysql.TINYINT(display_width=1), server_default='0', nullable=False),
    sa.Column('primary_sku_key', sa.String(length=128), sa.Computed('IF(is_primary = 1, internal_sku, NULL)', persisted=True), nullable=True, comment='生成列：is_primary=1 时为 internal_sku，否则 NULL'),
    sa.Column('has_conflict', mysql.TINYINT(display_width=1), server_default='0', nullable=False),
    sa.Column('conflict_detail', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sku_mappings')),
    sa.UniqueConstraint('shop_id', 'platform_sku', name='uk_sku_mappings_shop_platform_sku'),
    comment='SKU 映射'
    )
    with op.batch_alter_table('sku_mappings', schema=None) as batch_op:
        batch_op.create_index('idx_sku_mappings_internal', ['tenant_id', 'internal_sku'], unique=False)
        batch_op.create_index('idx_sku_mappings_shop', ['shop_id', 'internal_sku'], unique=False)
        batch_op.create_index(batch_op.f('idx_sku_mappings_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('uk_sku_mappings_primary', ['shop_id', 'primary_sku_key'], unique=True)

    op.create_table('state_transitions',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('machine', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('from_state', sa.String(length=64), nullable=True),
    sa.Column('to_state', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.String(length=16), server_default='SYSTEM', nullable=False),
    sa.Column('actor_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('context', mysql.JSON(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_state_transitions')),
    comment='状态转换事件（append-only）'
    )
    with op.batch_alter_table('state_transitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_state_transitions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('idx_transitions_entity', ['machine', 'entity_id', 'created_at'], unique=False)
        batch_op.create_index('idx_transitions_state', ['tenant_id', 'machine', 'to_state', 'created_at'], unique=False)
        batch_op.create_index('idx_transitions_trace', ['trace_id'], unique=False)

    op.create_table('sync_cursors',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('shop_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('cursor_type', sa.String(length=32), server_default='TIMESTAMP', nullable=False),
    sa.Column('cursor_value', sa.Text(), nullable=True),
    sa.Column('last_success_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('last_attempt_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='IDLE', nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_cursors')),
    sa.UniqueConstraint('shop_id', 'resource', name='uk_sync_cursors_shop_resource'),
    comment='同步游标'
    )
    with op.batch_alter_table('sync_cursors', schema=None) as batch_op:
        batch_op.create_index('idx_sync_cursors_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_sync_cursors_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('sync_watermarks',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('shop_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('last_full_check_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('last_incremental_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('data_max_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('fresh_lag_minutes', sa.Integer(), nullable=True),
    sa.Column('record_count', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('integrity_status', sa.String(length=32), server_default='UNKNOWN', nullable=False),
    sa.Column('gap_detail', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_watermarks')),
    sa.UniqueConstraint('shop_id', 'resource', name='uk_sync_watermarks_shop_resource'),
    comment='同步水位与完整性'
    )
    with op.batch_alter_table('sync_watermarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_sync_watermarks_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('task_runs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('shop_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('resource', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='RUNNING', nullable=False),
    sa.Column('started_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('finished_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('is_first_attempt', mysql.TINYINT(display_width=1), server_default='1', nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_processed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('params', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_runs')),
    comment='任务执行记录'
    )
    with op.batch_alter_table('task_runs', schema=None) as batch_op:
        batch_op.create_index('idx_task_runs_name', ['tenant_id', 'task_name', 'started_at'], unique=False)
        batch_op.create_index('idx_task_runs_status', ['status', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_task_runs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('idx_task_runs_trace', ['trace_id'], unique=False)

    op.create_table('tenants',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False, comment='租户编码'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='租户名称'),
    sa.Column('status', sa.String(length=32), server_default='ACTIVE', nullable=False, comment='状态：ACTIVE/SUSPENDED/DELETED'),
    sa.Column('default_timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('max_shops', sa.Integer(), server_default='10', nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('code', name=op.f('uk_tenants_code')),
    comment='租户'
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index('idx_tenants_status', ['status'], unique=False)

    op.create_table('user_roles',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('role_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('granted_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', name='uk_user_roles_user_role'),
    comment='用户角色关联'
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_roles_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('idx_user_roles_user', ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False, comment='登录名'),
    sa.Column('display_name', sa.String(length=255), nullable=False, comment='显示名'),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='ACTIVE', nullable=False),
    sa.Column('is_superuser', mysql.TINYINT(display_width=1), server_default='0', nullable=False),
    sa.Column('last_login_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tenant_id', 'username', name='uk_users_tenant_username'),
    comment='用户'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_tenant_id'))
        batch_op.drop_index('idx_users_status')

    op.drop_table('users')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index('idx_user_roles_user')
        batch_op.drop_index(batch_op.f('idx_user_roles_tenant_id'))

    op.drop_table('user_roles')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index('idx_tenants_status')

    op.drop_table('tenants')
    with op.batch_alter_table('task_runs', schema=None) as batch_op:
        batch_op.drop_index('idx_task_runs_trace')
        batch_op.drop_index(batch_op.f('idx_task_runs_tenant_id'))
        batch_op.drop_index('idx_task_runs_status')
        batch_op.drop_index('idx_task_runs_name')

    op.drop_table('task_runs')
    with op.batch_alter_table('sync_watermarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_sync_watermarks_tenant_id'))

    op.drop_table('sync_watermarks')
    with op.batch_alter_table('sync_cursors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_sync_cursors_tenant_id'))
        batch_op.drop_index('idx_sync_cursors_status')

    op.drop_table('sync_cursors')
    with op.batch_alter_table('state_transitions', schema=None) as batch_op:
        batch_op.drop_index('idx_transitions_trace')
        batch_op.drop_index('idx_transitions_state')
        batch_op.drop_index('idx_transitions_entity')
        batch_op.drop_index(batch_op.f('idx_state_transitions_tenant_id'))

    op.drop_table('state_transitions')
    with op.batch_alter_table('sku_mappings', schema=None) as batch_op:
        batch_op.drop_index('uk_sku_mappings_primary')
        batch_op.drop_index(batch_op.f('idx_sku_mappings_tenant_id'))
        batch_op.drop_index('idx_sku_mappings_shop')
        batch_op.drop_index('idx_sku_mappings_internal')

    op.drop_table('sku_mappings')
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_shops_tenant_id'))
        batch_op.drop_index('idx_shops_status')
        batch_op.drop_index('idx_shops_platform')

    op.drop_table('shops')
    with op.batch_alter_table('shop_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_shop_credentials_tenant_id'))
        batch_op.drop_index('idx_shop_credentials_status')
        batch_op.drop_index('idx_shop_credentials_expiry')

    op.drop_table('shop_credentials')
    with op.batch_alter_table('settlement_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_settlement_records_tenant_id'))
        batch_op.drop_index('idx_settlement_records_status')

    op.drop_table('settlement_records')
    with op.batch_alter_table('settlement_fees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_settlement_fees_tenant_id'))
        batch_op.drop_index('idx_settlement_fees_settlement')
        batch_op.drop_index('idx_settlement_fees_order')
        batch_op.drop_index('idx_settlement_fees_matched')

    op.drop_table('settlement_fees')
    with op.batch_alter_table('scoring_rubrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_scoring_rubrics_tenant_id'))

    op.drop_table('scoring_rubrics')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_roles_tenant_id'))

    op.drop_table('roles')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_role_permissions_tenant_id'))
        batch_op.drop_index('idx_role_permissions_role')

    op.drop_table('role_permissions')
    with op.batch_alter_table('return_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_return_records_tenant_id'))
        batch_op.drop_index('idx_return_records_status')
        batch_op.drop_index('idx_return_records_order')

    op.drop_table('return_records')
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_refunds_tenant_id'))
        batch_op.drop_index('idx_refunds_status')
        batch_op.drop_index('idx_refunds_reason')
        batch_op.drop_index('idx_refunds_order')

    op.drop_table('refunds')
    with op.batch_alter_table('raw_payloads', schema=None) as batch_op:
        batch_op.drop_index('idx_raw_payloads_type')
        batch_op.drop_index(batch_op.f('idx_raw_payloads_tenant_id'))
        batch_op.drop_index('idx_raw_payloads_expiry')
        batch_op.drop_index('idx_raw_payloads_entity')

    op.drop_table('raw_payloads')
    with op.batch_alter_table('profit_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_profit_snapshots_tenant_id'))
        batch_op.drop_index('idx_profit_snapshots_sku')
        batch_op.drop_index('idx_profit_snapshots_lookup')

    op.drop_table('profit_snapshots')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_products_tenant_id'))
        batch_op.drop_index('idx_products_status')
        batch_op.drop_index('idx_products_brand')

    op.drop_table('products')
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_product_variants_tenant_id'))
        batch_op.drop_index(batch_op.f('idx_product_variants_product_id'))
        batch_op.drop_index('idx_product_variants_product')

    op.drop_table('product_variants')
    with op.batch_alter_table('product_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_product_listings_tenant_id'))
        batch_op.drop_index('idx_listings_submission')
        batch_op.drop_index('idx_listings_shop_status')
        batch_op.drop_index('idx_listings_product')
        batch_op.drop_index('idx_listings_item')

    op.drop_table('product_listings')
    with op.batch_alter_table('product_attributes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_product_attributes_tenant_id'))
        batch_op.drop_index(batch_op.f('idx_product_attributes_product_id'))

    op.drop_table('product_attributes')
    with op.batch_alter_table('pricing_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_pricing_rules_tenant_id'))
        batch_op.drop_index('idx_pricing_rules_active')

    op.drop_table('pricing_rules')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index('idx_price_history_time')
        batch_op.drop_index(batch_op.f('idx_price_history_tenant_id'))
        batch_op.drop_index('idx_price_history_sku')

    op.drop_table('price_history')
    with op.batch_alter_table('platform_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_platform_categories_tenant_id'))
        batch_op.drop_index('idx_platform_categories_parent')

    op.drop_table('platform_categories')
    with op.batch_alter_table('platform_capabilities', schema=None) as batch_op:
        batch_op.drop_index('idx_platform_capabilities_state')

    op.drop_table('platform_capabilities')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index('idx_permissions_resource')

    op.drop_table('permissions')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_orders_tenant_id'))
        batch_op.drop_index('idx_orders_status')
        batch_op.drop_index('idx_orders_shop_time')
        batch_op.drop_index('idx_orders_settle')
        batch_op.drop_index('idx_orders_buyer_hash')
        batch_op.drop_index('idx_orders_anomaly')

    op.drop_table('orders')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_order_items_tenant_id'))
        batch_op.drop_index('idx_order_items_sku')
        batch_op.drop_index(batch_op.f('idx_order_items_order_id'))
        batch_op.drop_index('idx_order_items_order')

    op.drop_table('order_items')
    with op.batch_alter_table('order_fees', schema=None) as batch_op:
        batch_op.drop_index('idx_order_fees_type')
        batch_op.drop_index(batch_op.f('idx_order_fees_tenant_id'))
        batch_op.drop_index('idx_order_fees_settlement')
        batch_op.drop_index('idx_order_fees_order')

    op.drop_table('order_fees')
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.drop_index('idx_feature_flags_expiry')

    op.drop_table('feature_flags')
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_exchange_rates_tenant_id'))
        batch_op.drop_index('idx_exchange_rates_lookup')

    op.drop_table('exchange_rates')
    with op.batch_alter_table('domain_events', schema=None) as batch_op:
        batch_op.drop_index('idx_domain_events_type')
        batch_op.drop_index(batch_op.f('idx_domain_events_tenant_id'))
        batch_op.drop_index('idx_domain_events_pending')
        batch_op.drop_index('idx_domain_events_aggregate')

    op.drop_table('domain_events')
    with op.batch_alter_table('credential_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_credential_audit_logs_tenant_id'))
        batch_op.drop_index('idx_cred_audit_shop')
        batch_op.drop_index('idx_cred_audit_actor')

    op.drop_table('credential_audit_logs')
    with op.batch_alter_table('cost_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cost_rules_tenant_id'))
        batch_op.drop_index('idx_cost_rules_active')

    op.drop_table('cost_rules')
    with op.batch_alter_table('cost_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cost_items_tenant_id'))
        batch_op.drop_index('idx_cost_items_sku')
        batch_op.drop_index('idx_cost_items_period')

    op.drop_table('cost_items')
    with op.batch_alter_table('config_items', schema=None) as batch_op:
        batch_op.drop_index('uk_config_items_active')
        batch_op.drop_index(batch_op.f('idx_config_items_tenant_id'))
        batch_op.drop_index('idx_config_items_lookup')

    op.drop_table('config_items')
    with op.batch_alter_table('category_schemas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_category_schemas_tenant_id'))
        batch_op.drop_index('idx_category_schemas_lookup')

    op.drop_table('category_schemas')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_events_type')
        batch_op.drop_index('idx_audit_events_trace')
        batch_op.drop_index(batch_op.f('idx_audit_events_tenant_id'))
        batch_op.drop_index('idx_audit_events_resource')
        batch_op.drop_index('idx_audit_events_actor')

    op.drop_table('audit_events')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_approvals_tenant_id'))
        batch_op.drop_index('idx_approvals_resource')
        batch_op.drop_index('idx_approvals_requester')
        batch_op.drop_index('idx_approvals_pending')
        batch_op.drop_index('idx_approvals_expiry')

    op.drop_table('approvals')
    with op.batch_alter_table('approval_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_approval_rules_tenant_id'))
        batch_op.drop_index('idx_approval_rules_active')

    op.drop_table('approval_rules')
    with op.batch_alter_table('approval_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_approval_actions_tenant_id'))
        batch_op.drop_index(batch_op.f('idx_approval_actions_approval_id'))
        batch_op.drop_index('idx_approval_actions_approval')

    op.drop_table('approval_actions')
    with op.batch_alter_table('api_call_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_api_logs_lookup')
        batch_op.drop_index('idx_api_logs_expiry')
        batch_op.drop_index('idx_api_logs_error')
        batch_op.drop_index(batch_op.f('idx_api_call_logs_tenant_id'))

    op.drop_table('api_call_logs')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('idx_alerts_type')
        batch_op.drop_index(batch_op.f('idx_alerts_tenant_id'))
        batch_op.drop_index('idx_alerts_open')
        batch_op.drop_index('idx_alerts_dedup')

    op.drop_table('alerts')
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_alert_rules_tenant_id'))
        batch_op.drop_index('idx_alert_rules_active')

    op.drop_table('alert_rules')
    with op.batch_alter_table('accounting_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_accounting_periods_tenant_id'))
        batch_op.drop_index('idx_accounting_periods_status')

    op.drop_table('accounting_periods')
    # ### end Alembic commands ###
